//! Cost engine over a pruned snapshot of the LiteLLM pricing database
//! (`model_prices_and_context_window.json`, filtered to the claude / gpt /
//! o-series / codex families token-tach actually meets in local ledgers).
//!
//! UI-free, like everything in src/core. The snapshot is embedded at build
//! time and parsed once at runtime by `Db.init`.

const std = @import("std");
const types = @import("types.zig");

/// Pruned LiteLLM snapshot, regenerated by re-running the prune script
/// against the upstream file (see PLAN.md "pricing" row).
const snapshot_json = @embedFile("fixtures/pricing/model_prices.json");

/// Per-model USD rates. Field names match the LiteLLM schema so the
/// snapshot parses straight into this struct; absent fields (many OpenAI
/// entries carry no cache-creation rate) default to 0, which makes the
/// cost formula's "missing rate contributes nothing" rule fall out for free.
pub const Rates = struct {
    input_cost_per_token: f64 = 0,
    output_cost_per_token: f64 = 0,
    cache_creation_input_token_cost: f64 = 0,
    cache_read_input_token_cost: f64 = 0,
    max_input_tokens: u64 = 0,
};

/// Pricing database.
///
/// Refresh seam (deliberately NOT implemented here — no network code in
/// core): a later `refresh(self, allocator, fetched_json: []const u8) !void`
/// can parse a freshly downloaded LiteLLM file into a new arena, swap
/// `models` + `arena` atomically under the app's single-threaded update
/// loop, and drop the old arena. Callers only ever hold a `*Db`, so the
/// swap is invisible to them; the embedded snapshot stays as the fallback
/// when the fetch fails.
pub const Db = struct {
    /// Owns every string and table in `models` and `unknown`.
    arena: std.heap.ArenaAllocator,
    models: std.StringArrayHashMapUnmanaged(Rates),
    /// Dedup'd model names that failed resolution, in first-seen order.
    unknown: std.StringArrayHashMapUnmanaged(void),

    /// Parse the embedded snapshot once. `allocator` backs the arena that
    /// owns all parsed data; call `deinit` to release it.
    pub fn init(allocator: std.mem.Allocator) !Db {
        var arena = std.heap.ArenaAllocator.init(allocator);
        errdefer arena.deinit();

        const parsed = try std.json.parseFromSliceLeaky(
            std.json.ArrayHashMap(Rates),
            arena.allocator(),
            snapshot_json,
            .{ .ignore_unknown_fields = true },
        );

        return .{
            .arena = arena,
            .models = parsed.map,
            .unknown = .empty,
        };
    }

    pub fn deinit(self: *Db) void {
        self.arena.deinit();
        self.* = undefined;
    }

    /// USD cost of one usage event billed at `model`'s rates:
    ///   input*in + output*out + cache_creation*cache_write + cache_read*cache_read
    /// Missing cache rates in the db contribute 0. Returns null (and records
    /// the name for `unknownModels`) when the model cannot be resolved —
    /// recording is why this takes `*Db` rather than `*const Db`.
    pub fn cost(self: *Db, model: []const u8, ev: types.UsageEvent) ?f64 {
        const rates = self.resolve(model) orelse {
            self.recordUnknown(model);
            return null;
        };
        const in: f64 = @floatFromInt(ev.input_tokens);
        const out: f64 = @floatFromInt(ev.output_tokens);
        const cc: f64 = @floatFromInt(ev.cache_creation_tokens);
        const cr: f64 = @floatFromInt(ev.cache_read_tokens);
        return in * rates.input_cost_per_token +
            out * rates.output_cost_per_token +
            cc * rates.cache_creation_input_token_cost +
            cr * rates.cache_read_input_token_cost;
    }

    /// Convenience: price the event at its own `ev.model`.
    pub fn costOf(self: *Db, ev: types.UsageEvent) ?f64 {
        return self.cost(ev.model, ev);
    }

    /// Model names that failed resolution so far, dedup'd, first-seen order.
    /// Backing storage lives in the db arena; valid until `deinit`.
    pub fn unknownModels(self: *const Db) []const []const u8 {
        return self.unknown.keys();
    }

    /// Rates lookup with three stages: exact key, normalized (provider
    /// prefix stripped, then lowercased), then fuzzy — the db key that is
    /// the longest substring of the model name, so dated variants like
    /// "claude-sonnet-5-20260203" resolve to "claude-sonnet-5".
    fn resolve(self: *const Db, model: []const u8) ?Rates {
        if (self.models.get(model)) |r| return r;

        // Strip provider prefix(es): "openrouter/anthropic/claude-x" → "claude-x".
        const base = if (std.mem.lastIndexOfScalar(u8, model, '/')) |i|
            model[i + 1 ..]
        else
            model;
        if (base.ptr != model.ptr) {
            if (self.models.get(base)) |r| return r;
        }

        // Lowercase into a stack buffer (model ids are short; skip the
        // stage rather than allocate if one somehow is not).
        var buf: [160]u8 = undefined;
        const lowered: ?[]const u8 = if (base.len <= buf.len)
            std.ascii.lowerString(&buf, base)
        else
            null;
        if (lowered) |l| {
            if (!std.mem.eql(u8, l, base)) {
                if (self.models.get(l)) |r| return r;
            }
        }

        // Fuzzy: longest db key that appears inside the name.
        var best: ?Rates = null;
        var best_len: usize = 0;
        for (self.models.keys(), self.models.values()) |key, rates| {
            if (key.len <= best_len) continue;
            const hay = lowered orelse base;
            if (std.mem.indexOf(u8, hay, key) != null) {
                best = rates;
                best_len = key.len;
            }
        }
        return best;
    }

    fn recordUnknown(self: *Db, model: []const u8) void {
        // Best-effort: an OOM here only loses the "N unpriced models" hint.
        const alloc = self.arena.allocator();
        const gop = self.unknown.getOrPut(alloc, model) catch return;
        if (!gop.found_existing) {
            gop.key_ptr.* = alloc.dupe(u8, model) catch {
                _ = self.unknown.swapRemove(model);
                return;
            };
        }
    }
};

// ---------------------------------------------------------------------------
// Tests. Rate literals below are hand-copied from the pruned snapshot at
// src/core/fixtures/pricing/model_prices.json — if the snapshot is
// regenerated with new upstream rates, update them here too.
// ---------------------------------------------------------------------------

const testing = std.testing;

fn testEvent(model: []const u8, in: u64, out: u64, cc: u64, cr: u64) types.UsageEvent {
    return .{
        .agent = .claude,
        .timestamp_ms = 0,
        .model = model,
        .input_tokens = in,
        .output_tokens = out,
        .cache_creation_tokens = cc,
        .cache_read_tokens = cr,
    };
}

test "snapshot parses and is populated" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    try testing.expect(db.models.count() > 100);
    // Spot-check a known entry survived the prune with its context window.
    const sonnet = db.models.get("claude-sonnet-5").?;
    try testing.expectEqual(@as(u64, 1_000_000), sonnet.max_input_tokens);
}

test "known-model cost math matches hand-computed rates" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();

    // claude-sonnet-5: in 2e-6, out 1e-5, cache_write 2.5e-6, cache_read 2e-7.
    // 1000*2e-6 + 500*1e-5 + 2000*2.5e-6 + 10000*2e-7
    //   = 0.002 + 0.005 + 0.005 + 0.002 = 0.014
    const c = db.cost("claude-sonnet-5", testEvent("claude-sonnet-5", 1000, 500, 2000, 10000)).?;
    try testing.expectApproxEqAbs(@as(f64, 0.014), c, 1e-12);

    // claude-fable-5: in 1e-5, out 5e-5. Tokens-only event.
    // 100*1e-5 + 200*5e-5 = 0.001 + 0.01 = 0.011
    const f = db.cost("claude-fable-5", testEvent("claude-fable-5", 100, 200, 0, 0)).?;
    try testing.expectApproxEqAbs(@as(f64, 0.011), f, 1e-12);
}

test "costOf prices the event's own model" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    const ev = testEvent("claude-fable-5", 100, 200, 0, 0);
    try testing.expectApproxEqAbs(@as(f64, 0.011), db.costOf(ev).?, 1e-12);
}

test "fuzzy resolution: dated suffix hits the base key" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    // Not a db key; "claude-sonnet-5" is its longest db-key substring.
    const dated = db.cost("claude-sonnet-5-20260203", testEvent("", 1000, 500, 2000, 10000)).?;
    const exact = db.cost("claude-sonnet-5", testEvent("", 1000, 500, 2000, 10000)).?;
    try testing.expectApproxEqAbs(exact, dated, 1e-12);
    try testing.expectEqual(@as(usize, 0), db.unknownModels().len);
}

test "provider prefix is stripped before matching" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    const ev = testEvent("", 100, 200, 0, 0);
    const bare = db.cost("claude-fable-5", ev).?;
    try testing.expectApproxEqAbs(bare, db.cost("anthropic/claude-fable-5", ev).?, 1e-12);
    // Double prefix + mixed case exercises strip-then-lowercase.
    try testing.expectApproxEqAbs(bare, db.cost("openrouter/anthropic/Claude-Fable-5", ev).?, 1e-12);
}

test "missing cache rates contribute zero" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    // gpt-5.2-codex has no cache_creation_input_token_cost in the snapshot
    // (in 1.75e-6, out 1.4e-5, cache_read 1.75e-7).
    // 1_000_000*1.75e-6 + 0 + 50_000*0 + 100_000*1.75e-7 = 1.75 + 0.0175
    const c = db.cost("gpt-5.2-codex", testEvent("", 1_000_000, 0, 50_000, 100_000)).?;
    try testing.expectApproxEqAbs(@as(f64, 1.7675), c, 1e-9);
}

test "unknown model returns null and is recorded once" {
    var db = try Db.init(testing.allocator);
    defer db.deinit();
    const ev = testEvent("", 100, 100, 0, 0);
    try testing.expectEqual(@as(?f64, null), db.cost("totally-made-up-model-9000", ev));
    try testing.expectEqual(@as(?f64, null), db.cost("totally-made-up-model-9000", ev));
    try testing.expectEqual(@as(?f64, null), db.cost("another-mystery", ev));
    const misses = db.unknownModels();
    try testing.expectEqual(@as(usize, 2), misses.len);
    try testing.expectEqualStrings("totally-made-up-model-9000", misses[0]);
    try testing.expectEqualStrings("another-mystery", misses[1]);
}
